In [275]:
import os
from glob import glob
import pandas as pd
from functools import reduce
from xml.etree import ElementTree as et

In [276]:
# Load all xl files and store in a list
xml_list = glob('./data_images/*.xml')

# data cleaning . replace \\ with /
xml_list = list(map(lambda x: x.replace('\\','/'),xml_list))

In [277]:
pip install pandas

Requirement already satisfied: pandas in c:\users\administrator\.pyenv\pyenv-win\versions\3.11.9\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\administrator\.pyenv\pyenv-win\versions\3.11.9\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\administrator\.pyenv\pyenv-win\versions\3.11.9\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\administrator\.pyenv\pyenv-win\versions\3.11.9\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\administrator\.pyenv\pyenv-win\versions\3.11.9\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [278]:
xml_list

['./data_images/000001.xml',
 './data_images/000002.xml',
 './data_images/000003.xml',
 './data_images/000004.xml',
 './data_images/000006.xml',
 './data_images/000008.xml',
 './data_images/000010.xml',
 './data_images/000011.xml',
 './data_images/000013.xml',
 './data_images/000014.xml',
 './data_images/000015.xml',
 './data_images/000018.xml',
 './data_images/000022.xml',
 './data_images/000025.xml',
 './data_images/000027.xml',
 './data_images/000028.xml',
 './data_images/000029.xml',
 './data_images/000031.xml',
 './data_images/000037.xml',
 './data_images/000038.xml',
 './data_images/000040.xml',
 './data_images/000043.xml',
 './data_images/000045.xml',
 './data_images/000049.xml',
 './data_images/000053.xml',
 './data_images/000054.xml',
 './data_images/000055.xml',
 './data_images/000056.xml',
 './data_images/000057.xml',
 './data_images/000058.xml',
 './data_images/000059.xml',
 './data_images/000062.xml',
 './data_images/000067.xml',
 './data_images/000068.xml',
 './data_images/000069.xml',
 './data_images/000070.xml',
 './data_images/000071.xml',
 './data_images/000074.xml',
 './data_images/000075.xml',
 './data_images/000076.xml',
 './data_images/000079.xml',
 './data_images/000080.xml',
 './data_images/000082.xml',
 './data_images/000084.xml',
 './data_images/000085.xml',
 './data_images/000086.xml',
 './data_images/000087.xml',
 './data_images/000088.xml',
 './data_images/000090.xml',
 './data_images/000092.xml',
 './data_images/000094.xml',
 './data_images/000096.xml',
 './data_images/000097.xml',
 './data_images/000098.xml',
 './data_images/000100.xml',
 './data_images/000103.xml',
 './data_images/000105.xml',
 './data_images/000106.xml',
 './data_images/000108.xml',
 './data_images/000111.xml',
 './data_images/000114.xml',
 './data_images/000115.xml',
 './data_images/000116.xml',
 './data_images/000119.xml',
 './data_images/000124.xml',
 './data_images/000126.xml',
 './data_images/000127.xml',
 './data_images/000128.xml',
 './data_images/000135.xml',
 './data_images/000136.xml',
 './data_images/000137.xml',
 './data_images/000139.xml',
 './data_images/000144.xml',
 './data_images/000145.xml',
 './data_images/000148.xml',
 './data_images/000149.xml',
 './data_images/000151.xml',
 './data_images/000152.xml',
 './data_images/000155.xml',
 './data_images/000157.xml',
 './data_images/000160.xml',
 './data_images/000166.xml',
 './data_images/000167.xml',
 './data_images/000168.xml',
 './data_images/000172.xml',
 './data_images/000175.xml',
 './data_images/000176.xml',
 './data_images/000178.xml',
 './data_images/000179.xml',
 './data_images/000181.xml',
 './data_images/000182.xml',
 './data_images/000183.xml',
 './data_images/000185.xml',
 './data_images/000186.xml',
 './data_images/000188.xml',
 './data_images/000191.xml',
 './data_images/000195.xml',
 './data_images/000196.xml',
 './data_images/000197.xml',
 './data_images/000199.xml',
 './data_images/000201.xml',
 './data_images/000202.xml',
 './data_images/000204.xml',
 './data_images/000205.xml',
 './data_images/000206.xml',
 './data_images/000212.xml',
 './data_images/000213.xml',
 './data_images/000216.xml',
 './data_images/000217.xml',
 './data_images/000223.xml',
 './data_images/000226.xml',
 './data_images/000227.xml',
 './data_images/000230.xml',
 './data_images/000231.xml',
 './data_images/000234.xml',
 './data_images/000237.xml',
 './data_images/000238.xml',
 './data_images/000239.xml',
 './data_images/000240.xml',
 './data_images/000243.xml',
 './data_images/000247.xml',
 './data_images/000248.xml',
 './data_images/000252.xml',
 './data_images/000253.xml',
 './data_images/000254.xml',
 './data_images/000255.xml',
 './data_images/000258.xml',
 './data_images/000260.xml',
 './data_images/000261.xml',
 './data_images/000264.xml',
 './data_images/000265.xml',
 './data_images/000267.xml',
 './data_images/000271.xml',
 './data_images/000272.xml',
 './data_images/000273.xml',
 './data_images/000274.xml',
 './data_images/000277.xml',
 './data_images/000279.xml',
 './data_images/000280.xml',
 './data_images/000281.xml',
 './data_images/000283.xml',
 './data_images/000284.xml',
 './data_images/000286.xml',
 './data_images/000287.xml',
 './data_images/000290.xml',
 './data_images/000291.xml',
 './data_images/000292.xml',
 './data_images/000293.xml',
 './data_images/000295.xml',
 './data_images/000297.xml',
 './data_images/000299.xml',
 './data_images/000300.xml',
 './data_images/000301.xml',
 './data_images/000309.xml',
 './data_images/000310.xml',
 './data_images/000313.xml',
 './data_images/000314.xml',
 './data_images/000315.xml',
 './data_images/000316.xml',
 './data_images/000319.xml',
 './data_images/000324.xml',
 './data_images/000326.xml',
 './data_images/000327.xml',
 './data_images/000330.xml',
 './data_images/000333.xml',
 './data_images/000335.xml',
 './data_images/000339.xml',
 './data_images/000341.xml',
 './data_images/000342.xml',
 './data_images/000345.xml',
 './data_images/000346.xml',
 './data_images/000348.xml',
 './data_images/000350.xml',
 './data_images/000351.xml',
 './data_images/000353.xml',
 './data_images/000356.xml',
 './data_images/000357.xml',
 './data_images/000358.xml',
 './data_images/000360.xml',
 './data_images/000361.xml',
 './data_images/000362.xml',
 './data_images/000364.xml',
 './data_images/000365.xml',
 './data_images/000366.xml',
 './data_images/000368.xml',
 './data_images/000369.xml',
 './data_images/000371.xml',
 './data_images/000375.xml',
 './data_images/000376.xml',
 './data_images/000377.xml',
 './data_images/000378.xml',
 './data_images/000383.xml',
 './data_images/000384.xml',
 './data_images/000385.xml',
 './data_images/000386.xml',
 './data_images/000388.xml',
 './data_images/000389.xml',
 './data_images/000390.xml',
 './data_images/000392.xml',
 './data_images/000393.xml',
 './data_images/000397.xml',
 './data_images/000398.xml',
 './data_images/000399.xml',
 './data_images/000401.xml',
 './data_images/000402.xml',
 './data_images/000405.xml',
 './data_images/000409.xml',
 './data_images/000410.xml',
 './data_images/000412.xml',
 './data_images/000413.xml',
 './data_images/000414.xml',
 './data_images/000415.xml',
 './data_images/000418.xml',
 './data_images/000421.xml',
 './data_images/000422.xml',
 './data_images/000423.xml',
 './data_images/000425.xml',
 './data_images/000426.xml',
 './data_images/000429.xml',
 './data_images/000432.xml',
 './data_images/000434.xml',
 './data_images/000436.xml',
 './data_images/000437.xml',
 './data_images/000440.xml',
 './data_images/000441.xml',
 './data_images/000442.xml',
 './data_images/000444.xml',
 './data_images/000445.xml',
 './data_images/000447.xml',
 './data_images/000449.xml',
 './data_images/000451.xml',
 './data_images/000452.xml',
 './data_images/000453.xml',
 './data_images/000455.xml',
 './data_images/000456.xml',
 './data_images/000457.xml',
 './data_images/000458.xml',
 './data_images/000465.xml',
 './data_images/000466.xml',
 './data_images/000467.xml',
 './data_images/000471.xml',
 './data_images/000472.xml',
 './data_images/000473.xml',
 './data_images/000475.xml',
 './data_images/000478.xml',
 './data_images/000479.xml',
 './data_images/000481.xml',
 './data_images/000485.xml',
 './data_images/000487.xml',
 './data_images/000488.xml',
 './data_images/000490.xml',
 './data_images/000493.xml',
 './data_images/000495.xml',
 './data_images/000497.xml',
 './data_images/000502.xml',
 './data_images/000504.xml',
 './data_images/000505.xml',
 './data_images/000506.xml',
 './data_images/000507.xml',
 './data_images/000510.xml',
 './data_images/000511.xml',
 './data_images/000512.xml',
 './data_images/000517.xml',
 './data_images/000521.xml',
 './data_images/000527.xml',
 './data_images/000529.xml',
 './data_images/000532.xml',
 './data_images/000533.xml',
 './data_images/000534.xml',
 './data_images/000536.xml',
 './data_images/000538.xml',
 './data_images/000539.xml',
 './data_images/000542.xml',
 './data_images/000546.xml',
 './data_images/000547.xml',
 './data_images/000548.xml',
 './data_images/000551.xml',
 './data_images/000553.xml',
 './data_images/000556.xml',
 './data_images/000557.xml',
 './data_images/000558.xml',
 './data_images/000560.xml',
 './data_images/000561.xml',
 './data_images/000562.xml',
 './data_images/000566.xml',
 './data_images/000567.xml',
 './data_images/000568.xml',
 './data_images/000569.xml',
 './data_images/000570.xml',
 './data_images/000571.xml',
 './data_images/000572.xml',
 './data_images/000573.xml',
 './data_images/000574.xml',
 './data_images/000575.xml',
 './data_images/000576.xml',
 './data_images/000578.xml',
 './data_images/000580.xml',
 './data_images/000584.xml',
 './data_images/000585.xml',
 './data_images/000586.xml',
 './data_images/000587.xml',
 './data_images/000593.xml',
 './data_images/000594.xml',
 './data_images/000595.xml',
 './data_images/000596.xml',
 './data_images/000600.xml',
 './data_images/000602.xml',
 './data_images/000603.xml',
 './data_images/000604.xml',
 './data_images/000606.xml',
 './data_images/000607.xml',
 './data_images/000611.xml',
 './data_images/000614.xml',
 './data_images/000615.xml',
 './data_images/000616.xml',
 './data_images/000617.xml',
 './data_images/000618.xml',
 './data_images/000621.xml',
 './data_images/000623.xml',
 './data_images/000624.xml',
 './data_images/000627.xml',
 './data_images/000629.xml',
 './data_images/000630.xml',
 './data_images/000631.xml',
 './data_images/000634.xml',
 './data_images/000636.xml',
 './data_images/000638.xml',
 './data_images/000639.xml',
 './data_images/000640.xml',
 './data_images/000641.xml',
 './data_images/000642.xml',
 './data_images/000643.xml',
 './data_images/000644.xml',
 './data_images/000646.xml',
 './data_images/000649.xml',
 './data_images/000650.xml',
 './data_images/000651.xml',
 './data_images/000652.xml',
 './data_images/000655.xml',
 './data_images/000658.xml',
 './data_images/000659.xml',
 './data_images/000662.xml',
 './data_images/000664.xml',
 './data_images/000665.xml',
 './data_images/000666.xml',
 './data_images/000668.xml',
 './data_images/000669.xml',
 './data_images/000670.xml',
 './data_images/000673.xml',
 './data_images/000674.xml',
 './data_images/000678.xml',
 './data_images/000679.xml',
 './data_images/000681.xml',
 './data_images/000683.xml',
 './data_images/000687.xml',
 './data_images/000691.xml',
 './data_images/000692.xml',
 './data_images/000693.xml',
 './data_images/000696.xml',
 './data_images/000697.xml',
 './data_images/000698.xml',
 './data_images/000701.xml',
 './data_images/000703.xml',
 './data_images/000704.xml',
 './data_images/000706.xml',
 './data_images/000708.xml',
 './data_images/000715.xml',
 './data_images/000716.xml',
 './data_images/000718.xml',
 './data_images/000719.xml',
 './data_images/000721.xml',
 './data_images/000722.xml',
 './data_images/000723.xml',
 './data_images/000724.xml',
 './data_images/000725.xml',
 './data_images/000727.xml',
 './data_images/000732.xml',
 './data_images/000734.xml',
 './data_images/000735.xml',
 './data_images/000736.xml',
 './data_images/000737.xml',
 './data_images/000741.xml',
 './data_images/000743.xml',
 './data_images/000744.xml',
 './data_images/000745.xml',
 './data_images/000747.xml',
 './data_images/000749.xml',
 './data_images/000751.xml',
 './data_images/000757.xml',
 './data_images/000758.xml',
 './data_images/000759.xml',
 './data_images/000762.xml',
 './data_images/000765.xml',
 './data_images/000766.xml',
 './data_images/000769.xml',
 './data_images/000773.xml',
 './data_images/000775.xml',
 './data_images/000778.xml',
 './data_images/000779.xml',
 './data_images/000781.xml',
 './data_images/000783.xml',
 './data_images/000784.xml',
 './data_images/000785.xml',
 './data_images/000788.xml',
 './data_images/000789.xml',
 './data_images/000790.xml',
 './data_images/000792.xml',
 './data_images/000795.xml',
 './data_images/000798.xml',
 './data_images/000801.xml',
 './data_images/000803.xml',
 './data_images/000807.xml',
 './data_images/000809.xml',
 './data_images/000811.xml',
 './data_images/000813.xml',
 './data_images/000817.xml',
 './data_images/000819.xml',
 './data_images/000821.xml',
 './data_images/000824.xml',
 './data_images/000825.xml',
 './data_images/000833.xml',
 './data_images/000835.xml',
 './data_images/000836.xml',
 './data_images/000837.xml',
 './data_images/000838.xml',
 './data_images/000839.xml',
 './data_images/000840.xml',
 './data_images/000841.xml',
 './data_images/000844.xml',
 './data_images/000846.xml',
 './data_images/000852.xml',
 './data_images/000853.xml',
 './data_images/000856.xml',
 './data_images/000858.xml',
 './data_images/000861.xml',
 './data_images/000864.xml',
 './data_images/000866.xml',
 './data_images/000869.xml',
 './data_images/000870.xml',
 './data_images/000873.xml',
 './data_images/000875.xml',
 './data_images/000877.xml',
 './data_images/000881.xml',
 './data_images/000883.xml',
 './data_images/000884.xml',
 './data_images/000886.xml',
 './data_images/000890.xml',
 './data_images/000891.xml',
 './data_images/000893.xml',
 './data_images/000894.xml',
 './data_images/000897.xml',
 './data_images/000901.xml',
 './data_images/000905.xml',
 './data_images/000907.xml',
 './data_images/000909.xml',
 './data_images/000910.xml',
 './data_images/000913.xml',
 './data_images/000914.xml',
 './data_images/000916.xml',
 './data_images/000922.xml',
 './data_images/000924.xml',
 './data_images/000925.xml',
 './data_images/000927.xml',
 './data_images/000928.xml',
 './data_images/000930.xml',
 './data_images/000932.xml',
 './data_images/000933.xml',
 './data_images/000938.xml',
 './data_images/000939.xml',
 './data_images/000940.xml',
 './data_images/000941.xml',
 './data_images/000942.xml',
 './data_images/000944.xml',
 './data_images/000945.xml',
 './data_images/000952.xml',
 './data_images/000953.xml',
 './data_images/000955.xml',
 './data_images/000956.xml',
 './data_images/000957.xml',
 './data_images/000959.xml',
 './data_images/000960.xml',
 './data_images/000961.xml',
 './data_images/000963.xml',
 './data_images/000968.xml',
 './data_images/000969.xml',
 './data_images/000970.xml',
 './data_images/000974.xml',
 './data_images/000975.xml',
 './data_images/000976.xml',
 './data_images/000978.xml',
 './data_images/000979.xml',
 './data_images/000981.xml',
 './data_images/000983.xml',
 './data_images/000984.xml',
 './data_images/000985.xml',
 './data_images/000986.xml',
 './data_images/000988.xml',
 './data_images/000990.xml',
 './data_images/000992.xml',
 './data_images/000994.xml',
 './data_images/000995.xml',
 './data_images/000998.xml',
 './data_images/001000.xml',
 './data_images/001003.xml',
 './data_images/001005.xml',
 './data_images/001006.xml',
 './data_images/001007.xml',
 './data_images/001013.xml',
 './data_images/001016.xml',
 './data_images/001019.xml',
 './data_images/001020.xml',
 './data_images/001021.xml',
 './data_images/001022.xml',
 './data_images/001023.xml',
 './data_images/001025.xml',
 './data_images/001026.xml',
 './data_images/001029.xml',
 './data_images/001030.xml',
 './data_images/001031.xml',
 './data_images/001032.xml',
 './data_images/001033.xml',
 './data_images/001034.xml',
 './data_images/001035.xml',
 './data_images/001037.xml',
 './data_images/001038.xml',
 './data_images/001039.xml',
 './data_images/001040.xml',
 './data_images/001044.xml',
 './data_images/001046.xml',
 './data_images/001047.xml',
 './data_images/001048.xml',
 './data_images/001049.xml',
 './data_images/001051.xml',
 './data_images/001054.xml',
 './data_images/001055.xml',
 './data_images/001058.xml',
 './data_images/001059.xml',
 './data_images/001063.xml',
 './data_images/001065.xml',
 './data_images/001067.xml',
 './data_images/001070.xml',
 './data_images/001075.xml',
 './data_images/001076.xml',
 './data_images/001080.xml',
 './data_images/001081.xml',
 './data_images/001085.xml',
 './data_images/001086.xml',
 './data_images/001087.xml',
 './data_images/001088.xml',
 './data_images/001089.xml',
 './data_images/001090.xml',
 './data_images/001094.xml',
 './data_images/001095.xml',
 './data_images/001096.xml',
 './data_images/001098.xml',
 './data_images/001099.xml',
 './data_images/001100.xml',
 './data_images/001103.xml',
 './data_images/001105.xml',
 './data_images/001108.xml',
 './data_images/001111.xml',
 './data_images/001114.xml',
 './data_images/001115.xml',
 './data_images/001116.xml',
 './data_images/001117.xml',
 './data_images/001118.xml',
 './data_images/001120.xml',
 './data_images/001122.xml',
 './data_images/001123.xml',
 './data_images/001126.xml',
 './data_images/001128.xml',
 './data_images/001131.xml',
 './data_images/001132.xml',
 './data_images/001133.xml',
 './data_images/001134.xml',
 './data_images/001135.xml',
 './data_images/001138.xml',
 './data_images/001139.xml',
 './data_images/001141.xml',
 './data_images/001146.xml',
 './data_images/001150.xml',
 './data_images/001153.xml',
 './data_images/001155.xml',
 './data_images/001157.xml',
 './data_images/001159.xml',
 './data_images/001162.xml',
 './data_images/001163.xml',
 './data_images/001165.xml',
 './data_images/001167.xml',
 './data_images/001169.xml',
 './data_images/001173.xml',
 './data_images/001177.xml',
 './data_images/001178.xml',
 './data_images/001179.xml',
 './data_images/001180.xml',
 './data_images/001181.xml',
 './data_images/001183.xml',
 './data_images/001188.xml',
 './data_images/001189.xml',
 './data_images/001190.xml',
 './data_images/001193.xml',
 './data_images/001195.xml',
 './data_images/001196.xml',
 './data_images/001197.xml',
 './data_images/001198.xml',
 './data_images/001202.xml',
 './data_images/001208.xml',
 './data_images/001210.xml',
 './data_images/001213.xml',
 './data_images/001216.xml',
 './data_images/001217.xml',
 './data_images/001218.xml',
 './data_images/001219.xml',
 './data_images/001220.xml',
 './data_images/001222.xml',
 './data_images/001223.xml',
 './data_images/001227.xml',
 './data_images/001228.xml',
 './data_images/001232.xml',
 './data_images/001235.xml',
 './data_images/001238.xml',
 './data_images/001242.xml',
 './data_images/001243.xml',
 './data_images/001244.xml',
 './data_images/001245.xml',
 './data_images/001246.xml',
 './data_images/001249.xml',
 './data_images/001251.xml',
 './data_images/001252.xml',
 './data_images/001253.xml',
 './data_images/001255.xml',
 './data_images/001256.xml',
 './data_images/001257.xml',
 './data_images/001261.xml',
 './data_images/001262.xml',
 './data_images/001264.xml',
 './data_images/001267.xml',
 './data_images/001271.xml',
 './data_images/001275.xml',
 './data_images/001276.xml',
 './data_images/001278.xml',
 './data_images/001280.xml',
 './data_images/001282.xml',
 './data_images/001283.xml',
 './data_images/001285.xml',
 './data_images/001291.xml',
 './data_images/001295.xml',
 './data_images/001296.xml',
 './data_images/001297.xml',
 './data_images/001300.xml',
 './data_images/001301.xml',
 './data_images/001302.xml',
 './data_images/001303.xml',
 './data_images/001305.xml',
 './data_images/001306.xml',
 './data_images/001307.xml',
 './data_images/001308.xml',
 './data_images/001313.xml',
 './data_images/001317.xml',
 './data_images/001318.xml',
 './data_images/001319.xml',
 './data_images/001320.xml',
 './data_images/001321.xml',
 './data_images/001322.xml',
 './data_images/001328.xml',
 './data_images/001329.xml',
 './data_images/001331.xml',
 './data_images/001335.xml',
 './data_images/001336.xml',
 './data_images/001338.xml',
 './data_images/001339.xml',
 './data_images/001340.xml',
 './data_images/001342.xml',
 './data_images/001344.xml',
 './data_images/001347.xml',
 './data_images/001349.xml',
 './data_images/001351.xml',
 './data_images/001353.xml',
 './data_images/001354.xml',
 './data_images/001355.xml',
 './data_images/001356.xml',
 './data_images/001357.xml',
 './data_images/001358.xml',
 './data_images/001359.xml',
 './data_images/001363.xml',
 './data_images/001366.xml',
 './data_images/001367.xml',
 './data_images/001368.xml',
 './data_images/001369.xml',

In [279]:
# step-2: read xml files
# from each xml file we need to extract
# filename, size(width, height), object(name, xmin, xmax, ymin, ymax)
def extract_text(filename):
    tree = et.parse(filename)
    root =tree.getroot()

    # extract filename
    image_name = root.find('filename').text
    # Width and height of the image
    width = root.find('size').find('width').text
    height = root.find('size').find('height').text

    objs = root.findall('object')
    parser = []
    for obj in objs:
        name=obj.find('name').text
        bndbox = obj.find('bndbox')
        xmin = bndbox.find('xmin').text
        xmax = bndbox.find('xmax').text
        ymin = bndbox.find('ymin').text
        ymax = bndbox.find('ymax').text
        parser.append([image_name, width, height, name, xmin, xmax, ymin, ymax])

    return parser

In [280]:
parser_all = list(map(extract_text, xml_list))
parser_all

[[['000001.jpg', '353', '500', 'dog', '48', '195', '240', '371'],
  ['000001.jpg', '353', '500', 'person', '8', '352', '12', '498']],
 [['000002.jpg', '335', '500', 'train', '139', '207', '200', '301']],
 [['000003.jpg', '500', '375', 'sofa', '123', '215', '155', '195'],
  ['000003.jpg', '500', '375', 'chair', '239', '307', '156', '205']],
 [['000004.jpg', '500', '406', 'car', '13', '84', '311', '362'],
  ['000004.jpg', '500', '406', 'car', '362', '500', '330', '389'],
  ['000004.jpg', '500', '406', 'car', '235', '334', '328', '375'],
  ['000004.jpg', '500', '406', 'car', '175', '252', '327', '364'],
  ['000004.jpg', '500', '406', 'car', '139', '189', '320', '359'],
  ['000004.jpg', '500', '406', 'car', '108', '150', '325', '353'],
  ['000004.jpg', '500', '406', 'car', '84', '121', '323', '350']],
 [['000006.jpg', '500', '375', 'pottedplant', '187', '282', '135', '242'],
  ['000006.jpg', '500', '375', 'diningtable', '154', '369', '209', '375'],
  ['000006.jpg', '500', '375', 'chair', '255', '366', '207', '375'],
  ['000006.jpg', '500', '375', 'chair', '298', '332', '195', '247'],
  ['000006.jpg', '500', '375', 'chair', '279', '308', '190', '231'],
  ['000006.jpg', '500', '375', 'chair', '137', '151', '192', '199'],
  ['000006.jpg', '500', '375', 'chair', '137', '156', '198', '212'],
  ['000006.jpg', '500', '375', 'chair', '138', '249', '211', '375']],
 [['000008.jpg', '500', '375', 'chair', '192', '364', '16', '249']],
 [['000010.jpg', '354', '480', 'horse', '87', '258', '97', '427'],
  ['000010.jpg', '354', '480', 'person', '133', '245', '72', '284']],
 [['000011.jpg', '500', '324', 'cat', '126', '330', '51', '308']],
 [['000013.jpg', '500', '375', 'cow', '299', '446', '160', '252']],
 [['000014.jpg', '500', '333', 'bus', '72', '302', '163', '228'],
  ['000014.jpg', '500', '333', 'car', '185', '500', '194', '316'],
  ['000014.jpg', '500', '333', 'car', '416', '500', '180', '222'],
  ['000014.jpg', '500', '333', 'person', '314', '344', '8', '65'],
  ['000014.jpg', '500', '333', 'person', '331', '361', '4', '61'],
  ['000014.jpg', '500', '333', 'person', '357', '401', '8', '61'],
  ['000014.jpg', '500', '333', 'car', '163', '267', '197', '244']],
 [['000015.jpg', '500', '375', 'bicycle', '77', '360', '136', '358']],
 [['000018.jpg', '380', '285', 'dog', '31', '358', '30', '279']],
 [['000022.jpg', '500', '332', 'horse', '68', '368', '103', '283'],
  ['000022.jpg', '500', '332', 'person', '186', '255', '44', '230']],
 [['000025.jpg', '500', '375', 'cow', '2', '59', '84', '248'],
  ['000025.jpg', '500', '375', 'cow', '68', '233', '115', '279'],
  ['000025.jpg', '500', '375', 'cow', '64', '377', '173', '373'],
  ['000025.jpg', '500', '375', 'person', '320', '496', '2', '375'],
  ['000025.jpg', '500', '375', 'person', '221', '341', '4', '374'],
  ['000025.jpg', '500', '375', 'person', '135', '220', '14', '148'],
  ['000025.jpg', '500', '375', 'cow', '69', '156', '43', '177'],
  ['000025.jpg', '500', '375', 'person', '58', '104', '54', '139'],
  ['000025.jpg', '500', '375', 'person', '279', '331', '1', '86'],
  ['000025.jpg', '500', '375', 'person', '320', '344', '22', '96'],
  ['000025.jpg', '500', '375', 'person', '337', '390', '1', '107']],
 [['000027.jpg', '486', '500', 'person', '174', '349', '101', '351']],
 [['000028.jpg', '375', '500', 'cat', '63', '374', '18', '500']],
 [['000029.jpg', '500', '331', 'dog', '56', '284', '63', '290']],
 [['000031.jpg', '500', '335', 'train', '41', '430', '77', '255']],
 [['000037.jpg', '500', '375', 'dog', '61', '464', '96', '339']],
 [['000038.jpg', '500', '375', 'bicycle', '159', '279', '178', '246'],
  ['000038.jpg', '500', '375', 'motorbike', '1', '43', '235', '315'],
  ['000038.jpg', '500', '375', 'person', '192', '261', '111', '240']],
 [['000040.jpg', '500', '332', 'bird', '1', '384', '52', '290']],
 [['000043.jpg', '333', '500', 'person', '174', '324', '229', '375'],
  ['000043.jpg', '333', '500', 'person', '5', '250', '145', '500'],
  ['000043.jpg', '333', '500', 'person', '19', '323', '6', '500']],
 [['000045.jpg', '500', '375', 'tvmonitor', '280', '483', '64', '252']],
 [['000049.jpg', '500', '356', 'cat', '178', '356', '131', '227']],
 [['000053.jpg', '500', '375', 'cat', '36', '425', '12', '262']],
 [['000054.jpg', '500', '375', 'bus', '24', '472', '54', '292']],
 [['000055.jpg', '500', '333', 'motorbike', '209', '275', '132', '222'],
  ['000055.jpg', '500', '333', 'person', '219', '273', '107', '187'],
  ['000055.jpg', '500', '333', 'person', '465', '483', '273', '324'],
  ['000055.jpg', '500', '333', 'person', '436', '456', '279', '327']],
 [['000056.jpg', '500', '334', 'horse', '165', '387', '60', '334']],
 [['000057.jpg', '500', '375', 'bird', '133', '385', '53', '358']],
 [['000058.jpg', '500', '375', 'person', '334', '436', '1', '373'],
  ['000058.jpg', '500', '375', 'person', '196', '309', '80', '326'],
  ['000058.jpg', '500', '375', 'person', '279', '334', '53', '267'],
  ['000058.jpg', '500', '375', 'motorbike', '29', '359', '109', '375']],
 [['000059.jpg', '375', '500', 'tvmonitor', '88', '142', '161', '206'],
  ['000059.jpg', '375', '500', 'tvmonitor', '177', '273', '135', '200'],
  ['000059.jpg', '375', '500', 'person', '110', '328', '210', '500'],
  ['000059.jpg', '375', '500', 'person', '72', '115', '272', '356'],
  ['000059.jpg', '375', '500', 'person', '125', '171', '274', '353'],
  ['000059.jpg', '375', '500', 'chair', '285', '349', '397', '500']],
 [['000062.jpg', '500', '333', 'sheep', '58', '271', '188', '310']],
 [['000067.jpg', '500', '272', 'aeroplane', '44', '450', '72', '210']],
 [['000068.jpg', '500', '375', 'bird', '27', '266', '45', '375']],
 [['000069.jpg', '500', '375', 'boat', '19', '424', '64', '190'],
  ['000069.jpg', '500', '375', 'person', '305', '390', '155', '375']],
 [['000070.jpg', '500', '375', 'pottedplant', '358', '378', '163', '197'],
  ['000070.jpg', '500', '375', 'pottedplant', '313', '358', '156', '198']],
 [['000071.jpg', '500', '375', 'car', '61', '443', '75', '274']],
 [['000074.jpg', '500', '375', 'car', '58', '475', '61', '283']],
 [['000075.jpg', '332', '500', 'dog', '102', '222', '83', '348']],
 [['000076.jpg', '500', '375', 'person', '63', '265', '78', '375'],
  ['000076.jpg', '500', '375', 'person', '257', '448', '75', '375'],
  ['000076.jpg', '500', '375', 'person', '362', '446', '130', '261'],
  ['000076.jpg', '500', '375', 'person', '472', '500', '157', '343'],
  ['000076.jpg', '500', '375', 'person', '457', '478', '209', '255'],
  ['000076.jpg', '500', '375', 'person', '439', '458', '170', '216'],
  ['000076.jpg', '500', '375', 'person', '247', '288', '142', '197'],
  ['000076.jpg', '500', '375', 'person', '44', '84', '162', '286'],
  ['000076.jpg', '500', '375', 'person', '77', '120', '157', '245'],
  ['000076.jpg', '500', '375', 'person', '1', '26', '159', '283'],
  ['000076.jpg', '500', '375', 'person', '24', '45', '174', '201']],
 [['000079.jpg', '500', '357', 'dog', '1', '390', '53', '357']],
 [['000080.jpg', '500', '375', 'boat', '440', '455', '226', '261'],
  ['000080.jpg', '500', '375', 'boat', '398', '421', '216', '306'],
  ['000080.jpg', '500', '375', 'boat', '307', '320', '229', '259'],
  ['000080.jpg', '500', '375', 'boat', '246', '269', '202', '282'],
  ['000080.jpg', '500', '375', 'boat', '187', '209', '223', '287'],
  ['000080.jpg', '500', '375', 'boat', '186', '210', '202', '263'],
  ['000080.jpg', '500', '375', 'boat', '70', '111', '243', '274'],
  ['000080.jpg', '500', '375', 'boat', '1', '38', '276', '300'],
  ['000080.jpg', '500', '375', 'boat', '12', '33', '240', '258']],
 [['000082.jpg', '500', '333', 'car', '22', '493', '93', '298'],
  ['000082.jpg', '500', '333', 'car', '1', '207', '1', '88']],
 [['000084.jpg', '500', '375', 'chair', '339', '390', '156', '235'],
  ['000084.jpg', '500', '375', 'chair', '291', '346', '171', '273'],
  ['000084.jpg', '500', '375', 'chair', '224', '263', '165', '185'],
  ['000084.jpg', '500', '375', 'chair', '142', '193', '174', '276'],
  ['000084.jpg', '500', '375', 'chair', '232', '291', '192', '303'],
  ['000084.jpg', '500', '375', 'sofa', '1', '139', '276', '375'],
  ['000084.jpg', '500', '375', 'diningtable', '156', '332', '182', '281']],
 [['000085.jpg', '500', '330', 'chair', '6', '218', '104', '278'],
  ['000085.jpg', '500', '330', 'diningtable', '181', '499', '175', '329'],
  ['000085.jpg', '500', '330', 'person', '22', '254', '70', '327'],
  ['000085.jpg', '500', '330', 'person', '338', '500', '12', '199']],
 [['000086.jpg', '500', '333', 'dog', '308', '356', '131', '173'],
  ['000086.jpg', '500', '333', 'dog', '224', '274', '143', '182'],
  ['000086.jpg', '500', '333', 'dog', '270', '298', '125', '153']],
 [['000087.jpg', '333', '500', 'train', '120', '318', '166', '204']],
 [['000088.jpg', '500', '375', 'train', '123', '500', '7', '365']],
 [['000090.jpg', '500', '333', 'chair', '193', '346', '65', '278'],
  ['000090.jpg', '500', '333', 'person', '33', '307', '33', '255'],
  ['000090.jpg', '500', '333', 'person', '140', '416', '209', '333']],
 [['000092.jpg', '500', '375', 'cat', '2', '413', '66', '333']],
 [['000094.jpg', '500', '333', 'motorbike', '16', '500', '1', '333'],
  ['000094.jpg', '500', '333', 'motorbike', '1', '144', '54', '161']],
 [['000096.jpg', '330', '500', 'person', '2', '176', '144', '500'],
  ['000096.jpg', '330', '500', 'person', '140', '330', '109', '500']],
 [['000097.jpg', '500', '375', 'sofa', '58', '270', '174', '285'],
  ['000097.jpg', '500', '375', 'chair', '1', '156', '220', '375'],
  ['000097.jpg', '500', '375', 'person', '208', '267', '139', '235']],
 [['000098.jpg', '360', '270', 'cat', '69', '317', '70', '162']],
 [['000100.jpg', '432', '256', 'train', '3', '432', '47', '222']],
 [['000103.jpg', '500', '375', 'car', '1', '47', '241', '276'],
  ['000103.jpg', '500', '375', 'car', '26', '85', '234', '265'],
  ['000103.jpg', '500', '375', 'car', '98', '143', '222', '252'],
  ['000103.jpg', '500', '375', 'car', '183', '203', '217', '230'],
  ['000103.jpg', '500', '375', 'car', '201', '213', '211', '223'],
  ['000103.jpg', '500', '375', 'car', '160', '179', '218', '229'],
  ['000103.jpg', '500', '375', 'car', '55', '93', '223', '238'],
  ['000103.jpg', '500', '375', 'car', '29', '61', '227', '236'],
  ['000103.jpg', '500', '375', 'car', '1', '30', '230', '242']],
 [['000105.jpg', '500', '333', 'boat', '22', '320', '1', '314'],
  ['000105.jpg', '500', '333', 'person', '202', '295', '71', '215'],
  ['000105.jpg', '500', '333', 'person', '170', '239', '107', '206']],
 [['000106.jpg', '500', '333', 'bird', '181', '368', '96', '252']],
 [['000108.jpg', '500', '375', 'dog', '313', '500', '131', '235'],
  ['000108.jpg', '500', '375', 'dog', '1', '305', '103', '262'],
  ['000108.jpg', '500', '375', 'sofa', '1', '500', '59', '375']],
 [['000111.jpg', '500', '375', 'person', '415', '500', '270', '375'],
  ['000111.jpg', '500', '375', 'person', '337', '356', '182', '206'],
  ['000111.jpg', '500', '375', 'person', '291', '309', '177', '202'],
  ['000111.jpg', '500', '375', 'person', '278', '300', '185', '212'],
  ['000111.jpg', '500', '375', 'person', '233', '253', '176', '202'],
  ['000111.jpg', '500', '375', 'person', '221', '249', '184', '216'],
  ['000111.jpg', '500', '375', 'person', '185', '209', '187', '214'],
  ['000111.jpg', '500', '375', 'person', '178', '201', '177', '200'],
  ['000111.jpg', '500', '375', 'person', '149', '171', '186', '213'],
  ['000111.jpg', '500', '375', 'person', '112', '135', '186', '222'],
  ['000111.jpg', '500', '375', 'motorbike', '92', '141', '198', '227'],
  ['000111.jpg', '500', '375', 'bicycle', '142', '177', '206', '222'],
  ['000111.jpg', '500', '375', 'bicycle', '179', '213', '205', '222'],
  ['000111.jpg', '500', '375', 'bicycle', '174', '190', '192', '209'],
  ['000111.jpg', '500', '375', 'bicycle', '218', '251', '205', '216'],
  ['000111.jpg', '500', '375', 'bicycle', '242', '260', '197', '210'],
  ['000111.jpg', '500', '375', 'bicycle', '275', '306', '202', '216'],
  ['000111.jpg', '500', '375', 'bicycle', '302', '318', '198', '209'],
  ['000111.jpg', '500', '375', 'bicycle', '333', '362', '192', '210'],
  ['000111.jpg', '500', '375', 'chair', '345', '404', '230', '278']],
 [['000114.jpg', '500', '375', 'cat', '158', '432', '64', '365']],
 [['000115.jpg', '375', '500', 'bird', '1', '247', '219', '437']],
 [['000116.jpg', '375', '500', 'sofa', '44', '323', '189', '359'],
  ['000116.jpg', '375', '500', 'chair', '1', '45', '185', '302'],
  ['000116.jpg', '375', '500', 'pottedplant', '2', '106', '97', '273'],
  ['000116.jpg', '375', '500', 'pottedplant', '192', '277', '96', '202']],
 [['000119.jpg', '500', '375', 'cat', '107', '309', '96', '348']],
 [['000124.jpg', '500', '375', 'person', '2', '104', '6', '146'],
  ['000124.jpg', '500', '375', 'person', '230', '320', '25', '138'],
  ['000124.jpg', '500', '375', 'person', '78', '478', '15', '375'],
  ['000124.jpg', '500', '375', 'pottedplant', '70', '227', '2', '127'],
  ['000124.jpg', '500', '375', 'chair', '419', '500', '278', '375']],
 [['000126.jpg', '500', '215', 'diningtable', '429', '499', '176', '211'],
  ['000126.jpg', '500', '215', 'diningtable', '78', '259', '182', '215'],
  ['000126.jpg', '500', '215', 'diningtable', '291', '383', '162', '193'],
  ['000126.jpg', '500', '215', 'chair', '373', '433', '171', '214'],
  ['000126.jpg', '500', '215', 'chair', '351', '373', '165', '211'],
  ['000126.jpg', '500', '215', 'chair', '388', '418', '156', '175'],
  ['000126.jpg', '500', '215', 'chair', '316', '356', '165', '213'],
  ['000126.jpg', '500', '215', 'chair', '295', '310', '157', '164'],
  ['000126.jpg', '500', '215', 'chair', '281', '309', '158', '206'],
  ['000126.jpg', '500', '215', 'chair', '274', '282', '158', '171'],
  ['000126.jpg', '500', '215', 'chair', '259', '291', '172', '214'],
  ['000126.jpg', '500', '215', 'chair', '235', '260', '164', '186'],
  ['000126.jpg', '500', '215', 'chair', '252', '266', '159', '169'],
  ['000126.jpg', '500', '215', 'chair', '174', '208', '163', '180'],
  ['000126.jpg', '500', '215', 'chair', '117', '179', '179', '213'],
  ['000126.jpg', '500', '215', 'chair', '97', '129', '165', '189'],
  ['000126.jpg', '500', '215', 'chair', '123', '134', '164', '174'],
  ['000126.jpg', '500', '215', 'chair', '85', '94', '161', '189'],
  ['000126.jpg', '500', '215', 'chair', '53', '79', '162', '211'],
  ['000126.jpg', '500', '215', 'person', '458', '495', '136', '175'],
  ['000126.jpg', '500', '215', 'person', '47', '77', '139', '164'],
  ['000126.jpg', '500', '215', 'person', '37', '51', '140', '167'],
  ['000126.jpg', '500', '215', 'person', '12', '37', '140', '172']],
 [['000127.jpg', '500', '375', 'bird', '338', '427', '155', '234'],
  ['000127.jpg', '500', '375', 'bird', '312', '408', '192', '284'],
  ['000127.jpg', '500', '375', 'bird', '238', '341', '215', '318'],
  ['000127.jpg', '500', '375', 'bird', '173', '231', '226', '375'],
  ['000127.jpg', '500', '375', 'person', '68', '371', '21', '375']],
 [['000128.jpg', '500', '367', 'aeroplane', '53', '458', '117', '231'],
  ['000128.jpg', '500', '367', 'person', '356', '376', '235', '287'],
  ['000128.jpg', '500', '367', 'person', '387', '414', '204', '291'],
  ['000128.jpg', '500', '367', 'person', '152', '174', '207', '252'],
  ['000128.jpg', '500', '367', 'person', '99', '117', '203', '244'],
  ['000128.jpg', '500', '367', 'person', '8', '17', '206', '265'],
  ['000128.jpg', '500', '367', 'person', '33', '51', '211', '265'],
  ['000128.jpg', '500', '367', 'person', '51', '68', '219', '265']],
 [['000135.jpg', '500', '375', 'car', '208', '332', '194', '259']],
 [['000136.jpg', '500', '375', 'cat', '331', '407', '205', '267'],
  ['000136.jpg', '500', '375', 'bottle', '356', '374', '26', '70']],
 [['000137.jpg', '333', '500', 'car', '96', '164', '430', '482'],
  ['000137.jpg', '333', '500', 'person', '133', '142', '360', '390'],
  ['000137.jpg', '333', '500', 'person', '122', '135', '355', '392']],
 [['000139.jpg', '500', '334', 'bicycle', '114', '262', '124', '275'],
  ['000139.jpg', '500', '334', 'person', '151', '265', '52', '209'],
  ['000139.jpg', '500', '334', 'person', '1', '98', '173', '334']],
 [['000144.jpg', '500', '333', 'chair', '396', '477', '232', '330'],
  ['000144.jpg', '500', '333', 'diningtable', '135', '438', '191', '333'],
  ['000144.jpg', '500', '333', 'bottle', '221', '248', '192', '276'],
  ['000144.jpg', '500', '333', 'bottle', '245', '265', '156', '215'],
  ['000144.jpg', '500', '333', 'person', '2', '134', '100', '333'],
  ['000144.jpg', '500', '333', 'person', '166', '279', '66', '193'],
  ['000144.jpg', '500', '333', 'person', '351', '438', '3', '304'],
  ['000144.jpg', '500', '333', 'person', '344', '500', '8', '333']],
 [['000145.jpg', '500', '346', 'train', '52', '380', '88', '291'],
  ['000145.jpg', '500', '346', 'train', '412', '489', '132', '288']],
 [['000148.jpg', '500', '360', 'bird', '131', '465', '112', '312']],
 [['000149.jpg', '500', '375', 'pottedplant', '114', '351', '2', '361']],
 [['000151.jpg', '375', '500', 'bottle', '153', '375', '136', '264'],
  ['000151.jpg', '375', '500', 'person', '4', '375', '49', '440']],
 [['000152.jpg', '500', '333', 'car', '60', '123', '99', '152'],
  ['000152.jpg', '500', '333', 'car', '413', '500', '93', '156'],
  ['000152.jpg', '500', '333', 'car', '309', '421', '93', '141'],
  ['000152.jpg', '500', '333', 'car', '116', '405', '82', '285']],
 [['000155.jpg', '360', '500', 'bicycle', '94', '134', '51', '124'],
  ['000155.jpg', '360', '500', 'bicycle', '122', '168', '160', '255'],
  ['000155.jpg', '360', '500', 'bicycle', '223', '305', '288', '419'],
  ['000155.jpg', '360', '500', 'person', '89', '137', '7', '89'],
  ['000155.jpg', '360', '500', 'person', '114', '171', '120', '208'],
  ['000155.jpg', '360', '500', 'person', '221', '299', '250', '359']],
 [['000157.jpg', '400', '266', 'cat', '132', '378', '162', '224'],
  ['000157.jpg', '400', '266', 'chair', '34', '400', '35', '266']],
 [['000160.jpg', '500', '375', 'sofa', '2', '336', '242', '373']],
 [['000166.jpg', '500', '375', 'person', '324', '354', '170', '285'],
  ['000166.jpg', '500', '375', 'person', '243', '292', '180', '227'],
  ['000166.jpg', '500', '375', 'person', '2', '22', '170', '266'],
  ['000166.jpg', '500', '375', 'person', '26', '47', '178', '230'],
  ['000166.jpg', '500', '375', 'person', '67', '160', '114', '238'],
  ['000166.jpg', '500', '375', 'horse', '48', '229', '163', '334']],
 [['000167.jpg', '500', '374', 'dog', '27', '478', '18', '374']],
 [['000168.jpg', '318', '480', 'person', '72', '223', '102', '304'],
  ['000168.jpg', '318', '480', 'horse', '104', '201', '123', '471']],
 [['000172.jpg', '500', '375', 'car', '29', '456', '54', '321']],
 [['000175.jpg', '500', '332', 'sheep', '25', '419', '34', '271']],
 [['000176.jpg', '319', '480', 'sheep', '41', '148', '135', '288'],
  ['000176.jpg', '319', '480', 'sheep', '175', '287', '152', '284'],
  ['000176.jpg', '319', '480', 'sheep', '287', '319', '216', '277'],
  ['000176.jpg', '319', '480', 'sheep', '2', '83', '208', '278']],
 [['000178.jpg', '500', '375', 'bottle', '240', '288', '85', '254'],
  ['000178.jpg', '500', '375', 'bottle', '356', '397', '72', '216'],
  ['000178.jpg', '500', '375', 'bottle', '331', '362', '60', '166'],
  ['000178.jpg', '500', '375', 'bottle', '302', '335', '70', '158'],
  ['000178.jpg', '500', '375', 'bottle', '279', '310', '56', '162'],
  ['000178.jpg', '500', '375', 'bottle', '167', '204', '65', '180'],
  ['000178.jpg', '500', '375', 'bottle', '202', '251', '82', '244'],
  ['000178.jpg', '500', '375', 'bottle', '107', '139', '75', '134'],
  ['000178.jpg', '500', '375', 'bottle', '133', '156', '74', '113'],
  ['000178.jpg', '500', '375', 'person', '1', '102', '1', '216'],
  ['000178.jpg', '500', '375', 'person', '80', '203', '2', '120'],
  ['000178.jpg', '500', '375', 'person', '380', '500', '4', '210'],
  ['000178.jpg', '500', '375', 'person', '210', '351', '3', '92'],
  ['000178.jpg', '500', '375', 'person', '335', '394', '1', '107']],
 [['000179.jpg', '375', '500', 'boat', '269', '366', '420', '467'],

In [281]:
data = reduce(lambda x, y : x+y, parser_all)
df  = pd.DataFrame(data, columns = ['filename', 'width', 'height', 'name', 'xmin', 'xmax', 'ymin', 'ymax'])

In [282]:
df.head()

     filename width height    name xmin xmax ymin ymax
0  000001.jpg   353    500     dog   48  195  240  371
1  000001.jpg   353    500  person    8  352   12  498
2  000002.jpg   335    500   train  139  207  200  301
3  000003.jpg   500    375    sofa  123  215  155  195
4  000003.jpg   500    375   chair  239  307  156  205

In [283]:
df.shape

(14976, 8)

In [284]:
df['name'].value_counts()

name
person         5227
car            1541
chair          1374
bottle          657
pottedplant     592
bird            576
dog             530
sofa            396
horse           395
boat            393
bicycle         389
cat             370
motorbike       369
tvmonitor       361
cow             329
sheep           311
aeroplane       311
train           302
diningtable     299
bus             254
Name: count, dtype: int64

In [285]:
df['name']

0                dog
1             person
2              train
3               sofa
4              chair
            ...
14971         person
14972         person
14973         person
14974    diningtable
14975            car
Name: name, Length: 14976, dtype: str

In [286]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   filename  14976 non-null  str
 1   width     14976 non-null  str
 2   height    14976 non-null  str
 3   name      14976 non-null  str
 4   xmin      14976 non-null  str
 5   xmax      14976 non-null  str
 6   ymin      14976 non-null  str
 7   ymax      14976 non-null  str
dtypes: str(8)
memory usage: 936.1 KB

In [287]:
# type converison
cols = ['width','height','xmin','xmax', 'ymin','ymax']
df[cols] = df[cols].astype(int)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   filename  14976 non-null  str
 1   width     14976 non-null  int64
 2   height    14976 non-null  int64
 3   name      14976 non-null  str
 4   xmin      14976 non-null  int64
 5   xmax      14976 non-null  int64
 6   ymin      14976 non-null  int64
 7   ymax      14976 non-null  int64
dtypes: int64(6), str(2)
memory usage: 936.1 KB

In [288]:
# Center x, Center y
df['center_x'] =((df['xmax'] + df['xmin'])/2)/df['width']
df['center_y'] =((df['ymax'] + df['ymin'])/2)/df['height']

# w
df['w'] = (df['xmax'] - df['xmin'])/df['width']

#h
df['h'] = (df['ymax'] - df['ymin'])/df['height']

In [289]:
df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h
0,000001.jpg,353,500,dog,48,195,240,371,0.344193,0.611000,0.416431,0.262000
1,000001.jpg,353,500,person,8,352,12,498,0.509915,0.510000,0.974504,0.972000
2,000002.jpg,335,500,train,139,207,200,301,0.516418,0.501000,0.202985,0.202000
3,000003.jpg,500,375,sofa,123,215,155,195,0.338000,0.466667,0.184000,0.106667
4,000003.jpg,500,375,chair,239,307,156,205,0.546000,0.481333,0.136000,0.130667

### Split data into train and test

In [290]:
images = df['filename'].unique()

In [291]:
len(images)

4952

In [292]:
# 80% train and 20% test
img_df = pd.DataFrame(images, columns=['filename'])
img_train = tuple(img_df.sample(frac=0.8)['filename']) # shuffle and pick 80% of images

In [293]:
img_test = tuple(img_df.query(f'filename not in {img_train}')['filename']) # take rest 20% images

In [294]:
len(img_test)

990

In [295]:
len(img_train)

3962

In [296]:
train_df = df.query(f'filename in {img_train}')
test_df = df.query(f'filename in {img_test}')

In [297]:
train_df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h
2,000002.jpg,335,500,train,139,207,200,301,0.516418,0.501000,0.202985,0.202000
3,000003.jpg,500,375,sofa,123,215,155,195,0.338000,0.466667,0.184000,0.106667
4,000003.jpg,500,375,chair,239,307,156,205,0.546000,0.481333,0.136000,0.130667
5,000004.jpg,500,406,car,13,84,311,362,0.097000,0.828818,0.142000,0.125616
6,000004.jpg,500,406,car,362,500,330,389,0.862000,0.885468,0.276000,0.145320

In [298]:
test_df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h
0,000001.jpg,353,500,dog,48,195,240,371,0.344193,0.611000,0.416431,0.262000
1,000001.jpg,353,500,person,8,352,12,498,0.509915,0.510000,0.974504,0.972000
24,000013.jpg,500,375,cow,299,446,160,252,0.745000,0.549333,0.294000,0.245333
50,000031.jpg,500,335,train,41,430,77,255,0.471000,0.495522,0.778000,0.531343
52,000038.jpg,500,375,bicycle,159,279,178,246,0.438000,0.565333,0.240000,0.181333

## Assign id number to object names

In [299]:
# label encoding
def label_encoding(x):
    labels = {'person':0 ,'car':1, 'chair':2 , 'bottle':3, 'pottedplant':4, 'bird':5, 'dog':6, 'sofa':7, 'horse':8,
              'boat':9, 'bicycle':10, 'cat':11, 'motorbike':12, 'tvmonitor':13, 'cow':14, 'sheep':15, 'aeroplane':16, 
              'train':17, 'diningtable':18, 'bus':19}
    return labels[x]

In [300]:
train_df['id'] = train_df['name'].apply(label_encoding)
test_df['id'] = test_df['name'].apply(label_encoding)

In [301]:
train_df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h,id
2,000002.jpg,335,500,train,139,207,200,301,0.516418,0.501000,0.202985,0.202000,17
3,000003.jpg,500,375,sofa,123,215,155,195,0.338000,0.466667,0.184000,0.106667,7
4,000003.jpg,500,375,chair,239,307,156,205,0.546000,0.481333,0.136000,0.130667,2
5,000004.jpg,500,406,car,13,84,311,362,0.097000,0.828818,0.142000,0.125616,1
6,000004.jpg,500,406,car,362,500,330,389,0.862000,0.885468,0.276000,0.145320,1

## Save Image and Labels in text

In [302]:
import os
from shutil import move

In [303]:
train_folder = 'data_images/train'
test_folder = 'data_images/test'

os.mkdir(train_folder)
os.mkdir(test_folder)

In [304]:
cols = ['filename','id', 'center_x', 'center_y', 'w', 'h']
groupby_obj_train = train_df[cols].groupby('filename')
groupby_obj_test = test_df[cols].groupby('filename')

In [305]:
# save each image in train/test folder and respective labels in .txt
def save_data(filename, folder_path, group_obj):
    # move image
    src = os.path.join('data_images', filename)
    dst = os.path.join(folder_path,filename)
    move(src, dst) # move image to the destination folder

    # save the labels
    text_filename = os.path.join(folder_path,
                                 os.path.splitext(filename)[0]+'.txt')
    group_obj.get_group(filename).set_index('filename').to_csv(text_filename, sep=' ',index=False, header=False)

In [306]:
groupby_obj_train.groups

{'000002.jpg': [2], '000003.jpg': [3, 4], '000004.jpg': [5, 6, 7, 8, 9, 10, 11], '000006.jpg': [12, 13, 14, 15, 16, 17, 18, 19], '000008.jpg': [20], '000010.jpg': [21, 22], '000011.jpg': [23], '000014.jpg': [25, 26, 27, 28, 29, 30, 31], '000015.jpg': [32], '000018.jpg': [33], '000022.jpg': [34, 35], '000025.jpg': [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46], '000027.jpg': [47], '000028.jpg': [48], '000029.jpg': [49], '000037.jpg': [51], '000043.jpg': [56, 57, 58], '000045.jpg': [59], '000049.jpg': [60], '000053.jpg': [61], '000054.jpg': [62], '000055.jpg': [63, 64, 65, 66], '000056.jpg': [67], '000057.jpg': [68], '000059.jpg': [73, 74, 75, 76, 77, 78], '000062.jpg': [79], '000067.jpg': [80], '000068.jpg': [81], '000069.jpg': [82, 83], '000070.jpg': [84, 85], '000071.jpg': [86], '000075.jpg': [88], '000076.jpg': [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], '000079.jpg': [100], '000080.jpg': [101, 102, 103, 104, 105, 106, 107, 108, 109], '000082.jpg': [110, 111], '000084.jpg': [112, 113, 114, 115, 116, 117, 118], '000085.jpg': [119, 120, 121, 122], '000087.jpg': [126], '000088.jpg': [127], '000094.jpg': [132, 133], '000096.jpg': [134, 135], '000097.jpg': [136, 137, 138], '000100.jpg': [140], '000105.jpg': [150, 151, 152], '000106.jpg': [153], '000108.jpg': [154, 155, 156], '000111.jpg': [157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176], '000115.jpg': [178], '000116.jpg': [179, 180, 181, 182], '000119.jpg': [183], '000124.jpg': [184, 185, 186, 187, 188], '000126.jpg': [189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211], '000127.jpg': [212, 213, 214, 215, 216], '000128.jpg': [217, 218, 219, 220, 221, 222, 223, 224], '000135.jpg': [225], '000136.jpg': [226, 227], '000137.jpg': [228, 229, 230], '000139.jpg': [231, 232, 233], '000144.jpg': [234, 235, 236, 237, 238, 239, 240, 241], '000145.jpg': [242, 243], '000148.jpg': [244], '000151.jpg': [246, 247], '000152.jpg': [248, 249, 250, 251], '000157.jpg': [258, 259], '000160.jpg': [260], '000166.jpg': [261, 262, 263, 264, 265, 266], '000167.jpg': [267], '000168.jpg': [268, 269], '000172.jpg': [270], '000175.jpg': [271], '000176.jpg': [272, 273, 274, 275], '000178.jpg': [276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289], '000179.jpg': [290, 291, 292, 293, 294], '000181.jpg': [295, 296, 297, 298, 299, 300], '000182.jpg': [301, 302], '000183.jpg': [303], '000186.jpg': [307], '000188.jpg': [308, 309, 310, 311], '000191.jpg': [312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325], '000195.jpg': [326], '000196.jpg': [327, 328, 329, 330, 331], '000197.jpg': [332], '000199.jpg': [333], '000201.jpg': [334, 335, 336, 337, 338], '000204.jpg': [341], '000205.jpg': [342, 343, 344], '000206.jpg': [345, 346, 347, 348], '000212.jpg': [349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359], '000213.jpg': [360], '000216.jpg': [361], '000226.jpg': [373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384], '000227.jpg': [385, 386], '000230.jpg': [387, 388], '000231.jpg': [389, 390], '000234.jpg': [391, 392, 393, 394], '000237.jpg': [395, 396], '000238.jpg': [397, 398], '000239.jpg': [399, 400, 401], '000240.jpg': [402, 403, 404, 405, 406, 407, 408, 409, 410], ...}

In [307]:
filename_series = pd.Series(groupby_obj_train.groups.keys())
filename_series

0       000002.jpg
1       000003.jpg
2       000004.jpg
3       000006.jpg
4       000008.jpg
           ...
3957    009953.jpg
3958    009957.jpg
3959    009960.jpg
3960    009962.jpg
3961    009963.jpg
Length: 3962, dtype: str

In [308]:
filename_series.apply(save_data, args=(train_folder,groupby_obj_train))

0       None
1       None
2       None
3       None
4       None
        ...
3957    None
3958    None
3959    None
3960    None
3961    None
Length: 3962, dtype: object

In [309]:
filename_series_test = pd.Series(groupby_obj_test.groups.keys())
filename_series_test.apply(save_data, args=(test_folder,groupby_obj_test))

0      None
1      None
2      None
3      None
4      None
       ...
985    None
986    None
987    None
988    None
989    None
Length: 990, dtype: object